import React, { useState } from "react";
import axios from "axios";
import jsPDF from "jspdf";
import 'jspdf-autotable';

const Transaction = () => {
  const [fromDate, setFromDate] = useState("");
  const [toDate, setToDate] = useState("");
  const [report, setReport] = useState(null);

  const fetchReport = () => {
    if (!fromDate || !toDate) return alert("Select both dates");

    console.log("Fetching report with:", fromDate, toDate);

    axios.get(`https://localhost:7200/api/Transaction/report`, {
      params: { fromDate, toDate }
    })
    .then(res => {
      console.log("API Response:", res.data);
      setReport(res.data);
    })
    .catch(err => console.error("API Error:", err));
  };

  // ---------------- Generate PDF ----------------
  const generatePDF = () => {
    if (!report) return alert("No report to generate");

    const doc = new jsPDF();

    // Header
    doc.setFontSize(18);
    doc.text("Transaction Report", 14, 22);
    doc.setFontSize(12);
    doc.text(`Generated By: Sidra`, 14, 30);
    doc.text(`From: ${fromDate}  To: ${toDate}`, 14, 38);

    // Table data
    const tableColumn = ["Total Transactions", "Total Amount", "Total Tax", "Total Discount", "Net Revenue"];
    const tableRows = [
      [
        report.totalTransactions,
        report.totalAmount,
        report.totalTax,
        report.totalDiscount,
        report.netRevenue
      ]
    ];

    // Add table
    doc.autoTable({
      startY: 45,
      head: [tableColumn],
      body: tableRows
    });

    // Save PDF
    doc.save(`Transaction_Report_${fromDate}_to_${toDate}.pdf`);
  };

  return (
    <div>
      <h2>Transaction Report</h2>
      
      <div style={{ marginBottom: "20px", display: "flex", gap: "10px" }}>
        <div>
          <label>From: </label>
          <input type="date" value={fromDate} onChange={e => setFromDate(e.target.value)} />
        </div>
        <div>
          <label>To: </label>
          <input type="date" value={toDate} onChange={e => setToDate(e.target.value)} />
        </div>
        <button onClick={fetchReport}>Fetch Report</button>
        <button onClick={generatePDF} style={{ backgroundColor: "#4CAF50", color: "white" }}>Generate PDF</button>
      </div>

      {report && (
        <table border="1" cellPadding="10" style={{ width: "100%", borderCollapse: "collapse" }}>
          <thead>
            <tr>
              <th>Total Transactions</th>
              <th>Total Amount</th>
              <th>Total Tax</th>
              <th>Total Discount</th>
              <th>Net Revenue</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>{report.totalTransactions}</td>
              <td>{report.totalAmount}</td>
              <td>{report.totalTax}</td>
              <td>{report.totalDiscount}</td>
              <td>{report.netRevenue}</td>
            </tr>
          </tbody>
        </table>
      )}
    </div>
  );
};

export default Transaction;